services:
  shelbyappointments:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    environment:
      DB_URL: jdbc:postgresql://postgres-db:5432/shelby
      DB_USER_NAME: postgres
      DB_PASSWORD: admin
    depends_on:
      - postgres-db

  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-shelby
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shelby
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
